POST /verify/bvn/details
Host: localhost:2003/
Content-Type: application/json

{
	"bvn":"12345678901",
  "FirstName":"Uchenna",
  "MiddleName":"Chijioke",
  "LastName":"Nwanyanwu",
  "DateOfBirth":"22-Oct-1970",
  "PhoneNumber":"07033333333",
  "RegistrationDate":"16-Nov-2014",
  "EnrollmentBank":"900",
  "EnrollmentBranch":"Victoria Island",
  "WatchListed":"NO"
}
